"""esquema inicial

Revision ID: 418a070dfa63
Revises: 
Create Date: 2026-09-15 01:10:20.124653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '418a070dfa63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('environment', sa.String(length=20), server_default='lab', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment = 'lab'", name='ck_targets_solo_lab'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url', name='uq_targets_base_url')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), server_default='1.0.0', nullable=False),
    sa.Column('tool', sa.Enum('zap', 'nikto', 'openvas', name='herramienta'), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=300), nullable=True),
    sa.Column('source_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Bloque crudo de la herramienta, sin alterar. Es la evidencia que respalda todo lo demás.'),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('path_template', sa.String(length=1000), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('param', sa.String(length=200), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critica', 'alta', 'media', 'baja', 'informativa', name='severidad'), nullable=False),
    sa.Column('severity_tool_raw', sa.String(length=50), nullable=True),
    sa.Column('tool_confidence', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cwe_id', sa.Integer(), nullable=True),
    sa.Column('wasc_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=16), nullable=False),
    sa.Column('correlation_key', sa.String(length=16), nullable=True),
    sa.Column('occurrences', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('nuevo', 'en_triage', 'confirmado', 'falso_positivo', 'riesgo_aceptado', 'remediado', name='estado_hallazgo'), server_default='nuevo', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)', name='ck_findings_cvss_rango'),
    sa.CheckConstraint('occurrences >= 1', name='ck_findings_occurrences'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'dedupe_key', name='uq_findings_target_dedupe')
    )
    op.create_index('ix_findings_correlation', 'findings', ['correlation_key'], unique=False)
    op.create_index('ix_findings_cwe', 'findings', ['cwe_id'], unique=False)
    op.create_index('ix_findings_dashboard', 'findings', ['target_id', 'status', 'severity'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('tool', sa.Enum('zap', 'nikto', 'openvas', name='herramienta'), nullable=False),
    sa.Column('tool_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'ejecutando', 'importado', 'fallido', name='estado_escaneo'), server_default='pendiente', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_sha256', sa.String(length=64), nullable=True, comment='Hash del JSON crudo importado. Permite demostrar que el informe no se editó después.'),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Totales del escaneo: hallazgos, nuevos, enriquecidos, fallidos.'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scans_target_started', 'scans', ['target_id', 'started_at'], unique=False)
    op.create_table('ai_enrichments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('ok', 'failed', name='estado_ia'), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('owasp_version', sa.String(length=10), server_default='2025', nullable=True),
    sa.Column('owasp_category', sa.Enum('A01:2025', 'A02:2025', 'A03:2025', 'A04:2025', 'A05:2025', 'A06:2025', 'A07:2025', 'A08:2025', 'A09:2025', 'A10:2025', name='categoria_owasp'), nullable=True),
    sa.Column('priority', sa.Enum('p1', 'p2', 'p3', 'p4', name='prioridad'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('remediation_summary', sa.Text(), nullable=True),
    sa.Column('remediation_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.String(length=40), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('prompt_sha256', sa.String(length=64), nullable=True, comment='Hash del prompt exacto enviado. Permite reproducir la corrida.'),
    sa.CheckConstraint("state = 'failed' OR failure_reason IS NULL", name='ck_enrichment_motivo_solo_si_falla'),
    sa.CheckConstraint("state = 'ok' OR (owasp_category IS NULL AND priority IS NULL AND explanation IS NULL AND remediation_summary IS NULL)", name='ck_enrichment_fallo_sin_datos'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_enrichment_confianza_rango'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrichments_finding', 'ai_enrichments', ['finding_id'], unique=False)
    op.create_index('uq_enrichment_vigente', 'ai_enrichments', ['finding_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('finding_instances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('param', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instances_finding', 'finding_instances', ['finding_id'], unique=False)
    op.create_table('finding_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('instance_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'scan_id', name='uq_observacion_unica')
    )
    op.create_index('ix_observations_scan', 'finding_observations', ['scan_id'], unique=False)
    op.create_table('validations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('enrichment_id', sa.UUID(), nullable=True, comment='Qué salida de IA se estaba juzgando. Sin esto, comparar prompts es ambiguo.'),
    sa.Column('decision', sa.Enum('confirmado', 'falso_positivo', 'riesgo_aceptado', 'duplicado', 'requiere_segunda_opinion', name='decision_validacion'), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('priority_override', sa.Enum('p1', 'p2', 'p3', 'p4', name='prioridad'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ai_owasp_correcto', sa.Boolean(), nullable=True),
    sa.Column('ai_prioridad_correcta', sa.Boolean(), nullable=True),
    sa.Column('ai_remediacion_util', sa.Boolean(), nullable=True),
    sa.Column('ai_alucinacion', sa.Boolean(), nullable=True),
    sa.Column('ai_nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['enrichment_id'], ['ai_enrichments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validations_finding_fecha', 'validations', ['finding_id', 'reviewed_at'], unique=False)
    op.create_index('ix_validations_reviewer', 'validations', ['reviewer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validations_reviewer', table_name='validations')
    op.drop_index('ix_validations_finding_fecha', table_name='validations')
    op.drop_table('validations')
    op.drop_index('ix_observations_scan', table_name='finding_observations')
    op.drop_table('finding_observations')
    op.drop_index('ix_instances_finding', table_name='finding_instances')
    op.drop_table('finding_instances')
    op.drop_index('uq_enrichment_vigente', table_name='ai_enrichments', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_enrichments_finding', table_name='ai_enrichments')
    op.drop_table('ai_enrichments')
    op.drop_index('ix_scans_target_started', table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_findings_dashboard', table_name='findings')
    op.drop_index('ix_findings_cwe', table_name='findings')
    op.drop_index('ix_findings_correlation', table_name='findings')
    op.drop_table('findings')
    op.drop_table('targets')
    # ### end Alembic commands ###

    for tipo in ("herramienta", "severidad", "prioridad", "estado_hallazgo",
                 "estado_escaneo", "estado_ia", "categoria_owasp",
                 "decision_validacion"):
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
